version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: rbridge-client
    restart: always
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - client-dist:/app/dist

  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: rbridge-server
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "3000:3000" 

  db:
    image: postgres:14-alpine
    container_name: rbridge-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: rbridge-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  
      - client-dist:/usr/share/nginx/html  
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  client-dist: