INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (29, '看', '看-能发现有趣的点-人/动物所展现的', 'talent', NULL, '往往会有开心的状态，愿意“一起玩”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (30, '看', '看-能发现有趣的点-事/物所展现的', 'talent', NULL, '往往会有好奇或兴奋的状态，容易“玩起来”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (31, '看', '看-能发现有用的点-人所具备的', 'talent', NULL, '往往会展开“用”的行动，“为己所用”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (32, '看', '看-能发现有用的点-事/物所具备的', 'talent', NULL, '往往会展开“用”的行动，“物尽其材”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (33, '听', '听-能听出相同的点-熟悉内容', 'talent', NULL, '往往会强调或运用', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (34, '听', '听-能听出相同的点-不熟悉内容', 'talent', NULL, '往往会模仿或复述', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (35, '听', '听-能听出不同的点-需理解内容', 'talent', NULL, '往往会提问或思考', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (36, '听', '听-能听出不同的点-不需理解内容', 'talent', NULL, '往往会指出不同', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (37, '说', '说-能说出对方一听就明白的话-多人沟通', 'talent', NULL, '往往内容中自带因果逻辑，有助于推动共识', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (38, '说', '说-能说出对方一听就明白的话-一对一', 'talent', NULL, '往往包含自身认知与态度，有助于增进了解', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (39, '说', '说-能说出对方一听就被启发的话-分享', 'talent', NULL, '往往能引发思考与探讨', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (40, '说', '说-能说出对方一听就被启发的话-表演', 'talent', NULL, '往往能激发联想或想象', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (41, '记', '记-能记住有意义的内容-印象深刻的内容', 'talent', NULL, '往往引发过感共鸣或情绪波动，当再次表达时，常能感受到情感或情绪', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (42, '记', '记-能记住有意义的内容-得到启发的内容', 'talent', NULL, '往往触发过学习或思考，当分享时，常能体验到认知提升或知识增长', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (43, '记', '记-能记住有价值的内容-马上要用到', 'talent', NULL, '往往会很快看到用起来', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (44, '记', '记-能记住有价值的内容-将来能用到', 'talent', NULL, '在需要用的时候会想起来。或在未来，有可能有机会用起来', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (45, '想', '想-能想到奇特的点子-可预见实现时间', 'talent', NULL, '往往会去实现', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (46, '想', '想-能想到奇特的点子-不可预见实现时间', 'talent', NULL, '往往会去想象', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (47, '想', '想-能想到实用的点子-马上能用', 'talent', NULL, '往往会马上用于解决问题', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (48, '想', '想-能想到实用的点子-以后能用', 'talent', NULL, '往往来自对未来的推演', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (49, '做', '做-能把喜欢的事做得超出预期-短时间内能看到结果的', 'talent', NULL, '往往会很专注、很投入的做出好结果', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (50, '做', '做-能把喜欢的事做得超出预期-长周期才可能看到结果的', 'talent', NULL, '往往会很持续、很有热情的做出好结果', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (51, '做', '做-能把结果导向的事做得超出预期-短期内能实现结果的', 'talent', NULL, '往往在想做到的事上会很努力、很认真的做出好结果', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (52, '做', '做-能把结果导向的事做得超出预期-长周期能实现结果的', 'talent', NULL, '往往在想做到的事上会持续坚持、一步一步的做出好结果', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (53, '运动', '运动-调节性好-变化中调节', 'talent', NULL, '运动过程中往往会“玩出花来”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (54, '运动', '运动-调节性好-高速中调节', 'talent', NULL, '运动过程中往往会“玩出速度与激情”', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (55, '运动', '运动-适应性强-快速适应', 'talent', NULL, '运动过程中往往会迅速调整状态适应环境、或快速学习以满足需要', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (56, '运动', '运动-适应性强-长期适应', 'talent', NULL, '运动过程中往往会长期持续、乐此不疲', NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status,double_edged_id) VALUES (1, '看', '看-来自大自然或自然环境中-动的', 'like', 29, '经常主动观察动物；“看”时总有惊喜；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (2, '看', '看-来自大自然或自然环境中-静的', 'like', 30, '经常主动欣赏自然静物；“看”时总有不由自主开心起来的瞬间；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (3, '看', '看-人类学习/工作/生活环境中-与人相关的', 'like', 31, '经常主动观察人；“看”时总有不由自主傻乐起来的瞬间；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (4, '看', '看-人类学习/工作/生活环境中-与事/物相关的', 'like', 32, '经常主动观察事/物；“看”时总有惊奇；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (5, '听', '听-在接收中听-人/乐器声为主旋律的音/乐', 'like', 33, '经常主动欣赏音乐或倾听他人分享；“听”时总是很陶醉或很沉静的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (6, '听', '听-在接收中听-雨声/鸟鸣等自然之声', 'like', 34, '经常主动倾听自然之声；“听”时总是很愉悦或很放松的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (7, '听', '听-在交互中听-交谈', 'like', 35, '更乐于倾听交谈中的内容；“听”时总是会沉思或很专注的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (8, '听', '听-在交互中听-玩出声音，如玩乐器/玩具', 'like', 36, '经常主动玩出声音给自己听；“听”时总是会开心或很有兴致的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (9, '说', '说-互动-多人沟通', 'like', 37, '多人沟通时经常主动参与；“说”时总想尽量说明白；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (10, '说', '说-互动-一对一', 'like', 38, '经常主动发起一对一互动；“说”时总希望对方继续听下去；',NULL);   
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (11, '说', '说-演说-分享', 'like', 39, '经常主动分享各种自认为有价值的所思所想；“说”时总想尽量说精彩；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (12, '说', '说-演说-表演', 'like', 40, '经常不由自主的各种表演；“说”时总想让对方喝彩；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (13, '记', '记-自动记忆-生活中亲身体验过的', 'like', 41, '经常记起经历过的各种场景；“记”起时总觉得很特别；,“记”起时总觉得很特别；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (14, '记', '记-自动记忆-看书/影视作品等看到的或听说的', 'like', 42, '经常不知道在哪里“记”住了各种各样的东西；“记”起时总觉得很有趣；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (15, '记', '记-主动记忆-理解的', 'like', 43, '经常在理解后乐于记住；“记”时总觉得很有价值；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (16, '记', '记-主动记忆-不理解的', 'like', 44, '经常找到各种需要的东西主动“记”；“记”时总觉得很有用处；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (17, '想', '想-自然联想-与现实生活有关的', 'like', 45, '经常想象生活中可能会出现的场景；“想”时总觉得很好奇；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (18, '想', '想-自然联想-与现实生活无关的', 'like', 46, '经常不知道在“想”些什么；“想”时总觉得很有意思；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (19, '想', '想-刻意思考-想达到的', 'like', 47, '经常为目标达成不断思考；“想”时总觉得还可以想得更清楚；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (20, '想', '想-刻意思考-不需要达到的', 'like', 48, '经常为某种发现不停琢磨；“想”时总希望有更多新发现；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (21, '做', '做-能独立完成的-偏思维运算类', 'like', 49, '经常主动验证方法的“正确性”、想法的“可行性”；“做”的过程会很专注/很用心；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (22, '做', '做-能独立完成的-偏手工制作类', 'like', 50, '经常主动整理物件或艺术创作；“做”的过程会很投入/很安静；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (23, '做', '做-不能独立完成的-一对一协作', 'like', 51, '经常主动找喜欢的人一起做事；“做”的过程觉得能和喜欢的人在一起就很开心；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (24, '做', '做-不能独立完成的-多人协作', 'like', 52, '经常主动找大家一起做事；“做”的过程觉得能和大家在一起就很开心；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (25, '运动', '运动-技巧类-变化中协调', 'like', 53, '经常主动发起考验灵活性的各类活动；“运动”时总是很惬意的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (26, '运动', '运动-技巧类-移动中平衡', 'like', 54, '经常主动发起比拼平衡能力的各类活动；“运动”时总是很舒展的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (27, '运动', '运动-非技巧类-爆发时保持稳定', 'like', 55, '经常主动发起需要爆发力的各类活动；“运动”时总是很兴奋的样子；',NULL);
INSERT INTO elements (id, dimension, name, type, corresponding_element_id, status, double_edged_id) VALUES (28, '运动', '运动-非技巧类-持续中保持活力', 'like', 56, '经常主动发起挑战耐力的各类活动；“运动”时总是很有热情的样子；',NULL);
